import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {PointerLockControls} from 'three/addons/controls/PointerLockControls.js';

const $=id=>document.getElementById(id); const scene=new THREE.Scene(); scene.background=new THREE.Color(0xbfd8e4); scene.fog=new THREE.Fog(0xbfd8e4,170,520);
const camera=new THREE.PerspectiveCamera(55,1,.1,900); camera.position.set(135,105,150);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05; $('viewport').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.maxPolarAngle=Math.PI/2.02; controls.minDistance=55; controls.maxDistance=370; controls.target.set(0,0,0);
const fp=new PointerLockControls(camera,renderer.domElement); let walking=false; const keys={}; let joy={x:0,y:0};
scene.add(new THREE.HemisphereLight(0xeaf7ff,0x72806e,1.6)); const sun=new THREE.DirectionalLight(0xfff4dc,3.2); sun.position.set(-120,220,90); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); sun.shadow.camera.left=-300;sun.shadow.camera.right=300;sun.shadow.camera.top=300;sun.shadow.camera.bottom=-300;scene.add(sun);
const city=new THREE.Group(); scene.add(city); const pickables=[]; const mats={road:new THREE.MeshStandardMaterial({color:0x4b555b,roughness:.95}),side:new THREE.MeshStandardMaterial({color:0xc7c5bc,roughness:1}),grass:new THREE.MeshStandardMaterial({color:0x718d69,roughness:1}),glass:new THREE.MeshStandardMaterial({color:0x7ea9b7,metalness:.1,roughness:.28}),concrete:new THREE.MeshStandardMaterial({color:0xd7d5cf,roughness:.8}),dark:new THREE.MeshStandardMaterial({color:0x384650,roughness:.65}),roof:new THREE.MeshStandardMaterial({color:0x59666c,roughness:.8}),tree:new THREE.MeshStandardMaterial({color:0x4f7853,roughness:1}),trunk:new THREE.MeshStandardMaterial({color:0x715b43,roughness:1})};
function box(g,x,y,z,sx,sy,sz,m,cast=true){const q=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),m);q.position.set(x,y,z);q.castShadow=cast;q.receiveShadow=true;g.add(q);return q}
function cyl(g,x,y,z,r,h,m){const q=new THREE.Mesh(new THREE.CylinderGeometry(r,r*.88,h,10),m);q.position.set(x,y,z);q.castShadow=true;g.add(q);return q}
function road(x,z,w,d){box(city,x,-.12,z,w,.22,d,mats.road,false); for(let a=-Math.floor(w/12)*6;a<=Math.floor(w/12)*6;a+=12) box(city,x+a,.02,z,.35,.035,d*.88,new THREE.MeshStandardMaterial({color:0xd8c95d}),false)}
function tree(x,z,s=1){cyl(city,x,2*s,z,.45*s,4*s,mats.trunk);const c=new THREE.Mesh(new THREE.IcosahedronGeometry(2.8*s,1),mats.tree);c.position.set(x,5*s,z);c.castShadow=true;city.add(c)}
function windows(g,x,y,z,w,h,depth,count,vertical=true){const wm=new THREE.MeshStandardMaterial({color:0x6f9aa7,roughness:.22,metalness:.15}); for(let i=0;i<count;i++){let p=vertical?x-w/2+(i+.5)*w/count:x;let py=vertical?y:y-h/2+(i+.5)*h/count;let sx=vertical?w/count*.55:.12, sy=vertical:h*.58:h/count*.55; box(g,p,py,z, sx,sy,depth,wm,false)}}
function building(name,x,z,w,d,h,type){const g=new THREE.Group(); g.userData={name,type,area:w*d,height:h}; g.position.set(x,0,z); city.add(g); let body=box(g,0,h/2,0,w,h,d,type==='public'?mats.concrete:type==='research'?mats.glass:type==='industry'?mats.dark:new THREE.MeshStandardMaterial({color:0xd9d8d3,roughness:.72})); pickables.push(body);
  // facade rhythm
  const levels=Math.max(2,Math.floor(h/5)); const cols=Math.max(2,Math.floor(w/4));
  for(let l=0;l<levels;l++){const yy=3+l*5; if(yy>h-1) break; for(let c=0;c<cols;c++){const xx=-w/2+2+(c*(w-4)/Math.max(1,cols-1)); const wm=new THREE.MeshStandardMaterial({color:type==='public'?0x718e98:0x80a7ad,roughness:.25,metalness:.1}); box(g,xx,yy,d/2+.035,1.05,1.7,.08,wm,false); if(c<cols-1&&c%2===0) box(g,xx,yy,-d/2-.035,1.05,1.7,.08,wm,false)}}
  // roof equipment / parapet
  box(g,0,h+.55,0,w+.5,.9,d+.5,mats.roof); if(type==='public'){box(g,0,h+1.3,0,w*.42,.12,d*.42,mats.glass,false)}
  // podium
  box(g,0,1.2,0,w+2,2.4,d+2,type==='public'?mats.dark:mats.concrete);
  return g;
}
function sign(x,z,text){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#f8fafb';ctx.fillRect(0,0,512,128);ctx.fillStyle='#183746';ctx.font='bold 46px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,82);const t=new THREE.CanvasTexture(c);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));sp.scale.set(18,4.5,1);sp.position.set(x,12,z);city.add(sp)}
function car(x,z,rot=0,scale=1){const g=new THREE.Group();g.position.set(x,.8,z);g.rotation.y=rot;box(g,0,.55,0,5*scale,1.05,2.2*scale,mats.dark);box(g,0,1.25,0,2.7*scale,.9,1.75*scale,mats.glass);cyl(g,-1.8*scale,.15,-1.12*scale,.48*scale,.35*scale,new THREE.MeshStandardMaterial({color:0x22272b}));cyl(g,1.8*scale,.15,-1.12*scale,.48*scale,.35*scale,new THREE.MeshStandardMaterial({color:0x22272b}));cyl(g,-1.8*scale,.15,1.12*scale,.48*scale,.35*scale,new THREE.MeshStandardMaterial({color:0x22272b}));cyl(g,1.8*scale,.15,1.12*scale,.48*scale,.35*scale,new THREE.MeshStandardMaterial({color:0x22272b}));city.add(g);return g}
function person(x,z){const g=new THREE.Group();g.position.set(x,0,z);cyl(g,1,0,0,.25,2.1,new THREE.MeshStandardMaterial({color:0x485d69}));cyl(g,2.45,0,0,.22,.44,new THREE.MeshStandardMaterial({color:0xd8b18d}));city.add(g);return g}
function clearCity(){while(city.children.length)city.remove(city.children[0]);pickables.length=0}
function buildCity(){clearCity(); box(city,0,-.7,0,520,1.2,520,mats.grass,false); // arterial grid
 road(0,0,24,500); road(0,0,500,24); road(-145,0,14,500); road(145,0,14,500); road(0,-145,500,14); road(0,145,500,14); road(-75,0,10,500); road(75,0,10,500); road(0,-75,500,10); road(0,75,500,10);
 // parks
 box(city,-95,0,-95,62,.5,62,mats.grass,false); box(city,95,0,95,62,.5,62,mats.grass,false); for(let x=-120;x<=120;x+=15){tree(x,-120);tree(x,120)} for(let z=-120;z<=120;z+=15){tree(-120,z);tree(120,z)}
 const arr=[['광역교통센터',0,-42,34,28,18,'public'],['에너지정책원',-52,-20,26,22,32,'public'],['산업혁신청',-52,30,26,22,27,'public'],['지역R&D센터',-18,48,30,24,24,'research'],['대학·인재캠퍼스',42,45,48,30,15,'research'],['기업지원센터',54,8,28,24,22,'public'],['에너지 앵커기업',-45,78,46,30,20,'industry'],['첨단제조단지',-5,115,58,30,17,'industry'],['주거 A',95,-50,36,28,42,'res'],['주거 B',125,-5,30,28,32,'res'],['주거 C',100,42,42,30,48,'res'],['상업지구',45,-55,46,30,30,'res'],['의료·생활SOC',5,-105,42,28,16,'public'],['문화공원 복합센터',80,105,40,28,19,'public']];
 arr.forEach(a=>building(...a)); sign(0,-60,'METRO HUB');sign(45,28,'R&D CAMPUS');sign(50,-72,'COMMERCIAL');sign(-48,62,'PUBLIC');
 for(let i=0;i<24;i++){const a=i*Math.PI*2/24;car(Math.cos(a)*80,Math.sin(a)*80,a+.2,.7)} for(let i=0;i<45;i++)person((Math.random()-.5)*220,(Math.random()-.5)*220);
 // lamps
 for(let x=-135;x<=135;x+=30){for(const z of [-13,13]){box(city,x,5,z,.25,10,.25,mats.dark);cyl(city,x,10,z,.8,.15,new THREE.MeshStandardMaterial({color:0xf4e7ba,emissive:0x665d3c,emissiveIntensity:.4}))}}
}
buildCity();
function updateOutputs(){['inst','ind','uni','live','trans','firm'].forEach(k=>$(k+'O').textContent=$(k).value)}; document.querySelectorAll('input[type=range]').forEach(e=>e.addEventListener('input',updateOutputs));updateOutputs();
let currentYear=2026;
function calc(){const I=+$('inst').value,N=+$('ind').value,U=+$('uni').value,L=+$('live').value,T=+$('trans').value,F=+$('firm').value;const base=22000, years=currentYear-2026, q=(I*.18+N*.2+U*.15+L*.18+T*.16+F*.08);const pop=Math.round(base*(1+years*(.012+q/10000)));const firms=Math.round(F*(1+years*(.018+N/5000+U/7000)));const jobs=Math.round(firms*(34+N*.12));const vac=Math.max(3,Math.round(42-L*.18-T*.08-N*.06));const score=Math.min(100,Math.round(q+L*.12));$('pop').textContent=pop.toLocaleString();$('firms').textContent=firms.toLocaleString();$('jobs').textContent=jobs.toLocaleString();$('vac').textContent=vac+'%';$('score').style.width=score+'%';$('scoreT').textContent=score;$('year').textContent=currentYear;$('progress').style.width=((currentYear-2026)/20*100)+'%';$('status').textContent=currentYear+'년 · '+(currentYear===2026?'이전 준비 단계':currentYear<2032?'초기 정착 단계':currentYear<2040?'클러스터 성장 단계':'성숙·자립 단계')}
function advance(n){currentYear=Math.min(2046,Math.max(2026,currentYear+n));calc()}; $('minus').onclick=()=>advance(-1);$('plus').onclick=()=>advance(1);$('run').onclick=()=>{currentYear=2046;calc()};$('resetBtn').onclick=()=>{currentYear=2026;document.querySelectorAll('input[type=range]').forEach((e,i)=>e.value=[70,65,60,55,60,80][i]);updateOutputs();buildCity();calc()};$('apply').onclick=()=>{buildCity();calc()};calc();
$('walkBtn').onclick=()=>{walking=!walking; if(walking){controls.enabled=false;camera.position.set(0,7,105);fp.lock();$('mode').textContent='도시 진입 · 1인칭';$('crosshair').style.display='block';$('joystick').style.display='block'}else{fp.unlock();controls.enabled=true;$('mode').textContent='관찰 모드';$('crosshair').style.display='none';$('joystick').style.display='none'}};
window.addEventListener('keydown',e=>keys[e.code]=true);window.addEventListener('keyup',e=>keys[e.code]=false);
let down=null,lastX=0,lastY=0;renderer.domElement.addEventListener('pointerdown',e=>{down=e.pointerId;lastX=e.clientX;lastY=e.clientY});renderer.domElement.addEventListener('pointermove',e=>{if(!walking||down!==e.pointerId)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;camera.rotation.y-=dx*.004;camera.rotation.x-=dy*.003;camera.rotation.x=Math.max(-1.25,Math.min(1.25,camera.rotation.x))});window.addEventListener('pointerup',()=>down=null);
$('joystick').addEventListener('pointermove',e=>{const r=$('joystick').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=(e.clientX-cx)/42,y=(e.clientY-cy)/42;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len}joy={x,y};$('stick').style.transform=`translate(${x*28}px,${y*28}px)`});$('joystick').addEventListener('pointerup',()=>{joy={x:0,y:0};$('stick').style.transform=''});
function resize(){const r=$('viewport').getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}window.addEventListener('resize',resize);resize();$('loading').style.display='none';
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(walking){const f=(keys.KeyW||keys.ArrowUp?-1:keys.KeyS||keys.ArrowDown?1:0)+joy.y;const s=(keys.KeyD||keys.ArrowRight?1:keys.KeyA||keys.ArrowLeft?-1:0)+joy.x;const speed=22*dt;const dir=new THREE.Vector3();camera.getWorldDirection(dir);dir.y=0;dir.normalize();camera.position.addScaledVector(dir,-f*speed);const side=new THREE.Vector3().crossVectors(camera.up,dir).normalize();camera.position.addScaledVector(side,s*speed);camera.position.y=7;camera.position.x=THREE.MathUtils.clamp(camera.position.x,-240,240);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-240,240)}else controls.update();renderer.render(scene,camera)}animate();
renderer.domElement.addEventListener('click',e=>{if(walking)return;const r=renderer.domElement.getBoundingClientRect(),m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,camera);const hit=ray.intersectObjects(pickables)[0];if(hit){const d=hit.object.parent?.userData||hit.object.userData; if(d.name) $('status').textContent=`선택: ${d.name} · ${d.type} · ${Math.round(d.area)}㎡ · 높이 ${d.height}m`}});
